spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          filters:
          - name: HttpRequestCounter
            args:
              instanceTag: "uri.toString()" ## 取instanceId会返回null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true

server:
  port: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:12345/eureka